version: 1
services:
  my-app-runner-service:
    source:
      image: public.ecr.aws/your-ecr-repository:latest
    runtime: python3
    build:
      command: ["pip", "install", "-r", "requirements.txt"]
    environment:
      - FILE_PATH: /path/to/your/file.txt
      - S3_BUCKET_NAME: your-s3-bucket-name
      - MONGODB_URI: mongodb+srv://<username>:<password>@your-mongodb-cluster.mongodb.net
      - MONGODB_DATABASE: your-database-name
      - MONGODB_COLLECTION: your-collection-name
    ports:
      - 80
    healthCheck:
      command: "curl -f http://localhost/ || exit 1"
      interval: 5s
      timeout: 2s
      retries: 3
      startPeriod: 20s

